#!/usr/bin/env bash
# Run nginx as nginx user listening on port 8080
grep -q '^nginx:' /etc/passwd || useradd --system --no-create-home nginx
sed -i 's/^#*\s*user\s.*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80/listen 8080/g' /etc/nginx/sites-enabled/default
service nginx restart