#!/usr/bin/env bash
# Configures a new Ubuntu machine's Nginx to include a custom
# HTTP response header X-Served-By with the server's hostname
# shellcheck disable=SC2154

sudo apt-get -y update
sudo apt-get -y install nginx

sudo sed -i '/listen 80 default_server;/a add_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default

sudo service nginx restart