#!/usr/bin/env bash
# Install and configure HAProxy load balancer

sudo apt-get update
sudo apt-get -y install haproxy

echo "ENABLED=1" | sudo tee /etc/default/haproxy

sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOF

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 23.23.29.130 check
    server web-02 52.1.33.100 check
EOF

sudo service haproxy restart